USE alura_sql;

ALTER TABLE tb_cliente ADD PRIMARY KEY(CPF);

SELECT * FROM tb_produto;

SELECT * FROM tb_cliente;

ALTER TABLE tb_produto ADD COLUMN (DATA_NASCIMENTO DATE); 

ALTER TABLE tb_produto DROP COLUMN DATA_NASCIMENTO;

ALTER TABLE tb_cliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO tb_cliente (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO) VALUES 
(
	'00388934505', 
	'João da Silva', 
	'Rua projetada A número 10', 
	'', 
	'Vila Roman', 
	'CARATINGA', 
	'Amazonas', 
	'2222222', 
	30, 
	'M', 
	10000.00, 
	2000, 
	0, 
	'1989-10-05'
);